server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
    com.xiao.blog: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 1
    password: 123456
    timeout: 5000ms
  cache:
    #设置缓存类型
    type: redis
    redis:
      #缓存存活时间，不设置则没有过期时间
      time-to-live: 1800000ms
  mail:
    default-encoding: utf-8
    host: 220.181.12.18 #smtp.163.com 的ip地址
    port: 465
    username: xiaoj_2019@163.com
    password: Wangyi2019
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  activemq:
    #ActiveMQ的通讯地址
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    #是否启用内存模式（不安装MQ，项目启动时同时启动MQ实例）
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: false
mybatis:
  #加载mapper.xml文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  type-aliases-package: com.xiao.blog.**.domain




